name: sneakershoottest
description: Flutter Sneakershoot tes
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  stacked: ^1.6.0
  provider: ^4.1.3
  get_it: ^4.0.2
  http: ^0.12.1
  auto_route: ^0.5.0
  # see below for explanation
  stacked_services: ^0.4.1
  injectable: ^0.4.0+1
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true
